# This workflow will build a Godot .NET project
# For more information see: https://github.com/marketplace/actions/build-godot

name: "godot-ci export"
on:
  pull_request:
  push:
    branches: 
      - develop

env:
  GODOT_VERSION: 3.5.1
  EXPORT_NAME: "starswarm-develop"
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  ITCH_PROJECT_NAME: "star-swarm"
  ITCH_USERNAME: "capnbootyberry"

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:mono-3.5.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable.mono ~/.local/share/godot/templates/${GODOT_VERSION}.stable.mono
      - name: Make Exports Folder
        run: |
          mkdir -v exports
      - name: Windows Build
        run: |
          mkdir -v ./exports/windows
          godot -v --export "Windows Desktop" ./exports/windows/$EXPORT_NAME.exe
      - name: Publish Export Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exports
          path: exports
  push-to-itch:
    needs: export-windows
    if: ${{ contains(github.ref, 'develop') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Exports
        uses: actions/download-artifact@v3
        with:
          name: exports
          path: exports
      - name: Zip Exports
        run: |
          cd exports/windows
          zip -r starswarm.zip $EXPORT_NAME.exe $EXPORT_NAME.pck
          cd ../..
      - name: Download + Authorize Butler
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V
      - name: Login To Butler
        run: ./butler login
      - name: Push Windows Export To Itch
        run: ./butler push exports/windows/starswarm.zip $ITCH_USERNAME/$ITCH_PROJECT_NAME:win
